name: fayvad-geosolutions

services:
  # Your Django app
  web:
    build: .

    env_file:
      .env.prod

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    ports:
      - "8000:8000"

    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn fayvad_geosolutions.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - app-network

    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      web:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network
    command: >
      sh -c "sleep 10 && nginx -g 'daemon off;'"

volumes:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge 