# Generated by Django 4.2.7 on 2025-06-21 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("client_name", models.CharField(max_length=200)),
                ("client_organization", models.CharField(max_length=200)),
                (
                    "short_description",
                    models.TextField(
                        help_text="Brief description for cards", max_length=300
                    ),
                ),
                (
                    "detailed_description",
                    models.TextField(help_text="Full project description"),
                ),
                (
                    "location",
                    models.CharField(help_text="Project location", max_length=200),
                ),
                (
                    "area_covered",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '251 km', '1,200 hectares'",
                        max_length=100,
                    ),
                ),
                (
                    "project_value",
                    models.CharField(
                        blank=True, help_text="e.g., 'KES 50M', '€540K'", max_length=100
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g., '18 months', '2021-2024'", max_length=100
                    ),
                ),
                (
                    "challenge",
                    models.TextField(help_text="Project challenge/problem statement"),
                ),
                ("solution", models.TextField(help_text="Our solution/approach")),
                ("results", models.TextField(help_text="Project results/outcomes")),
                (
                    "services_provided",
                    models.JSONField(
                        default=list, help_text="List of services provided"
                    ),
                ),
                (
                    "technologies_used",
                    models.JSONField(
                        default=list, help_text="Technologies and tools used"
                    ),
                ),
                (
                    "team_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Team size", null=True
                    ),
                ),
                (
                    "key_metrics",
                    models.JSONField(
                        default=dict, help_text="Key metrics as JSON object"
                    ),
                ),
                (
                    "success_metrics",
                    models.JSONField(
                        default=list, help_text="Success metrics/achievements"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="projects/"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High Priority"),
                            ("medium", "Medium Priority"),
                            ("low", "Low Priority"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                (
                    "is_case_study",
                    models.BooleanField(
                        default=True, help_text="Available as detailed case study"
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False, help_text="Limit public details"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(help_text="Emoji or icon class", max_length=50),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1e3c72", help_text="Hex color code", max_length=7
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Project Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("update_date", models.DateField()),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Overall project progress (0-100)",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Show to public"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-update_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_title", models.CharField(max_length=200)),
                ("client_organization", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="Rating out of 5"),
                ),
                ("date_given", models.DateField(auto_now_add=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_given"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTagging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.project",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projecttag",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "tag")},
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_achieved", models.DateField()),
                (
                    "is_major",
                    models.BooleanField(default=False, help_text="Major milestone"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["date_achieved", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Alt text for accessibility", max_length=200
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload project documents, reports, etc.",
                        upload_to="projects/files/",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the file", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the file"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Report', 'Presentation', 'Data'",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Show to public visitors"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="portfolio.projectcategory",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for this project",
                through="portfolio.ProjectTagging",
                to="portfolio.projecttag",
            ),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("award", "Award"),
                            ("certification", "Certification"),
                            ("recognition", "Recognition"),
                            ("milestone", "Milestone"),
                            ("publication", "Publication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("awarding_body", models.CharField(blank=True, max_length=200)),
                ("date_achieved", models.DateField()),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True, help_text="Link to certificate/documentation"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Award value if applicable",
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="🏆", help_text="Emoji or icon", max_length=50
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related project (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_achieved", "order"],
            },
        ),
    ]
